### ISSUE TITLE
一个插件目录下能否有多个入口dll

### ISSUE THREAD

**Issue by tky753** [xfrogcn/Xfrogcn.PluginFactory#1]
比如我的插件是类似于ABP架构的： Domain(定义实体)、EfCore(数据库操作)、AppService(应用服务)，
EfCore 引用 Domain，
AppService 引用 Domain，
但EfCore 和 AppService 就没有引用关系，
所以必修要同时加载这两个模块才行。
如果改成从插件目录下的一个配置文件中获取需加载的dll，是否会更好？

**Comment by tky753** [comment]
还是不要多个入口了，用IsolationAssemblyLoadContext动态加载EfCore和AppService后，发现加载了两份的Domain，明明引用的是同一个dll，我想了想，应该是因为两个LoadContext是相互独立的。
@xfrogcn  不考虑一下多种加载方式吗，既可以隔离开来，也可以就用默认的AssemblyLoadContext.Default一个dll一个dll依次加载

**Comment by xfrogcn** [comment]
> 还是不要多个入口了，用IsolationAssemblyLoadContext动态加载EfCore和AppService后，发现加载了两份的Domain，明明引用的是同一个dll，我想了想，应该是因为两个LoadContext是相互独立的。
> @xfrogcn 不考虑一下多种加载方式吗，既可以隔离开来，也可以就用默认的AssemblyLoadContext.Default一个dll一个dll依次加载

1. 多入口dll从框架角度考虑，可能不太合适。
2. 公共dll可以考虑放到APP目录，而不是插件目录，插件目录中dll都是独立加载的，但如果依赖dll在插件目录不存在，则会默认使用应用目录中的dll

**Comment by tky753** [comment]
有道理，最好别用多入口，公共dll这个没办法放到APP目录，因为就对于这个插件用得到
不过为了以防万一，我可能会考虑一个插件目录一个LoadContext，万一有多个入口的话就共用一个LoadContext，这样子折中应该就能解决大部分问题了吧。
